services:
  metastore:
    image: postgres:11
    container_name: hadoop_postgres
    hostname: metastore
    environment:
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - ~/Documents/Docker-Volumns/hadoop/metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.0.1
    extra_hosts:
      - "master:172.28.0.2"
      - "worker1:172.28.0.3"
      - "worker2:172.28.0.4"
      - "history:172.28.0.5"

  master:
    image: hadoop-hive-spark-master
    container_name: hadoop_master
    hostname: master
    tty: true
    depends_on:
      - metastore
    environment:
      SPARK_MASTER_HOST: 172.28.0.2
      SPARK_LOCAL_IP: 172.28.0.2
      SPARK_LOCAL_HOSTNAME: master
    ports:
      - "4040:4040"
      - "8020:8020"
      - "8080:8080"
      - "8088:8088"
      - "9870:9870"
      - "10000:10000"
    volumes:
      - ~/Documents/Docker-Volumns/hadoop/namenode:/opt/hadoop/dfs/name
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.0.2
    extra_hosts:
      - "metastore:172.28.0.1"
      - "worker1:172.28.0.3"
      - "worker2:172.28.0.4"
      - "history:172.28.0.5"

  worker1:
    image: hadoop-hive-spark-worker
    container_name: hadoop_worker1
    hostname: worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.0.2
      SPARK_LOCAL_IP: 172.28.0.3
      SPARK_LOCAL_HOSTNAME: worker1
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    volumes:
      - ~/Documents/Docker-Volumns/hadoop/datanode1:/opt/hadoop/dfs/data
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.0.3
    extra_hosts:
      - "metastore:172.28.0.1"
      - "master:172.28.0.2"
      - "worker2:172.28.0.4"
      - "history:172.28.0.5"

  worker2:
    image: hadoop-hive-spark-worker
    container_name: hadoop_worker2
    hostname: worker2
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.0.2
      SPARK_LOCAL_IP: 172.28.0.4
      SPARK_LOCAL_HOSTNAME: worker2
    ports:
      - "8043:8042"
      - "8082:8081"
      - "9865:9864"
    volumes:
      - ~/Documents/Docker-Volumns/hadoop/datanode2:/opt/hadoop/dfs/data
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.0.4
    extra_hosts:
      - "metastore:172.28.0.1"
      - "master:172.28.0.2"
      - "worker1:172.28.0.3"
      - "history:172.28.0.5"

  history:
    image: hadoop-hive-spark-history
    container_name: hadoop_history
    hostname: history
    depends_on:
      - master
      - worker1
      - worker2
    environment:
      SPARK_MASTER_HOST: 172.28.0.2
      SPARK_LOCAL_IP: 172.28.0.5
      SPARK_LOCAL_HOSTNAME: history
    ports:
      - "18080:18080"
      - "19888:19888"
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.0.5
    extra_hosts:
      - "metastore:172.28.0.1"
      - "master:172.28.0.2"
      - "worker1:172.28.0.3"
      - "worker2:172.28.0.4"

  # jupyter:
  #   image: hadoop-hive-spark-jupyter
  #   hostname: jupyter
  #   environment:
  #     SPARK_MASTER_HOST: 172.28.0.2
  #     SPARK_LOCAL_IP: 172.28.0.6
  #     SPARK_LOCAL_HOSTNAME: jupyter
  #   depends_on:
  #     - master
  #     - worker1
  #     - worker2
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./jupyter/notebook:/home/jupyter
  #   restart: always
  #   networks:
  #     sparknet:
  #       ipv4_address: 172.28.0.6
  #   extra_hosts:
  #     - "metastore:172.28.0.1"
  #     - "master:172.28.0.2"
  #     - "worker1:172.28.0.3"
  #     - "worker2:172.28.0.4"
  #     - "history:172.28.0.5"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]

  dev:
    image: hadoop-hive-spark-dev
    container_name: hadoop_dev
    hostname: dev
    tty: true
    environment:
      SPARK_MASTER_HOST: 172.28.0.2
      SPARK_LOCAL_IP: 172.28.0.7
      SPARK_LOCAL_HOSTNAME: dev
    volumes:
      - ~/Documents/Docker-Volumns/hadoop/hadoop-dev:/home/
    networks:
      sparknet:
        ipv4_address: 172.28.0.7
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

# volumes:
#   namenode: 
#   namesecondary:
#   datanode1:
#   datanode2:
#   metastore:

networks:
  sparknet:
    external: true